spring:
  docker:
    compose:
      skip:
        in-tests: true
  datasource:
    username: sa
    password:
    url: jdbc:h2:mem:testdb
    hikari:
      username: sa
      password:
      jdbc-url: jdbc:h2:mem:testdb
      driver-class-name: org.h2.Driver
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
