services:
  postgres:
    image: localhost:5001/postgres-pgvector
    container_name: int-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - authorization-server-postgres:/var/lib/postgresql/data
    ports:
      - 5433:5432
volumes:
  authorization-server-postgres:
