services:
  authorization-server-postgres:
    image: localhost:5001/postgres-pgvector
    container_name: authorization-server-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - authorization-postgres:/var/lib/postgresql/data
    ports:
      - "5433:5432"
volumes:
  authorization-postgres:
